[template]
src = "ircdd.tmpl"

dest = "/etc/ircdd/ircdd.yaml"

keys = [ 
    "/services/rethinkdb",
    "/services/nsqlookupd",
]

reload_cmd="pkill twistd && twistd --logfile=/var/log/ircdd.log ircdd --config=/etc/ircdd/ircdd.yaml --nsqd_tcp_address=$HOST_IP:$NSQD_PORT --hostname=$INSTANCE_NAME" 
